import type { Metadata } from "next";
import { Roboto_Slab, Roboto_Mono, Inter, Roboto, Merriweather, Nunito, Instrument_Sans } from "next/font/google";
import "./globals.css";
import CardNav from "./components/CardNav/CardNav";
import Footer from "./components/Footer";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});
// The homepage design is set in Instrument Sans throughout.
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    label: "Home",
    bgColor: "#EFE7A3",
    textColor: "#2F2100",
    links: [{ label: "Home", href: "/" }],
  },
  {
    label: "Who We Are",
    bgColor: "#E9DF90",
    textColor: "#2F2100",
    links: [
      { label: "Our Expertise", href: "/expertise" },
      { label: "Our Professionals", href: "/professionals" },
      { label: "About", href: "/about" },
    ],
  },
  {
    label: "News",
    bgColor: "#E3D77D",
    textColor: "#2F2100",
    links: [
      { label: "Publications", href: "/publications" },
      { label: "Contact", href: "/contact" },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${robotoMono.variable} ${inter.variable} ${roboto.variable} ${merriweather.variable} ${nunito.variable} ${instrumentSans.variable}`}>
        <CardNav
          logo="/logo-icon.svg"
          logoAlt="Firm logo"
          firmName="PROF. Z. ADANGOR (SAN) & CO"
          items={navItems}
          contactEmail="Zacchaeusadangor@nigerianbar.ng"
          baseColor="#F7F3C6"
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
