import type { Metadata } from "next";
import { Roboto_Slab, Roboto_Mono } from "next/font/google";
import "./globals.css";
import CardNav from "./components/CardNav/CardNav";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    label: "Home",
    bgColor: "#1A2340",
    textColor: "#fff",
    links: [{ label: "Home", href: "/" }],
  },
  {
    label: "Who We Are",
    bgColor: "#242D4D",
    textColor: "#fff",
    links: [
      { label: "Our Workplace", href: "/workplace" },
      { label: "Our Impact", href: "/impact" },
    ],
  },
  {
    label: "News",
    bgColor: "#242D4D",
    textColor: "#fff",
    links: [{ label: "Latest News", href: "/news" }],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${robotoMono.variable}`}>
        <CardNav
          firmName="PROF. Z. ADANGOR (SAN) & CO"
          items={navItems}
          contactEmail="Zacchaeusadangor@nigerianbar.ng"
        />
        {children}
      </body>
    </html>
  );
}
